# Generated by Django 3.0.4 on 2020-03-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medRegApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='medical_leaving_date',
            field=models.DateField(),
        ),
    ]
