# Generated by Django 3.0.4 on 2020-03-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medRegApp', '0002_auto_20200321_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='help_seeker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medRegApp.HelpSeeker'),
            preserve_default=False,
        ),
    ]
