# Generated by Django 3.0.4 on 2020-03-21 21:37

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('medRegApp', '0003_helprequest_help_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Karlsruhe', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='49.0134, 8.4014', max_length=63),
        ),
    ]
