# Generated by Django 3.0.4 on 2020-03-22 08:54

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('medRegApp', '0004_auto_20200321_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is_admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='current_medical_occupation',
            field=models.BooleanField(default=False, verbose_name='current_medical_occupation'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='current_occupation',
            field=models.CharField(max_length=100, verbose_name='current_occupation'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is_available'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='medical_leaving_date',
            field=models.DateField(verbose_name='medical_leaving_date'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='medRegApp.Qualification', verbose_name='qualifications'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='description',
            field=models.TextField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='end_date',
            field=models.DateField(verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='helpers',
            field=models.ManyToManyField(blank=True, to='medRegApp.Helper', verbose_name='helpers'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='required_helper_count',
            field=models.IntegerField(verbose_name='required_helper_count'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Karlsruhe', max_length=255, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='49.0134, 8.4014', max_length=63, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
